/* AUTO-GENERATED by tools/train_model.py; DO NOT EDIT.
 * Depth-7 decision tree, 83 nodes, held-out window accuracy 0.8871.
 * Input: float f[11] in the exact order of model/features_nogravity.json.
 * Returns fault code: 0=healthy 1=loose_mount 2=rotor_drag 3=overheat
 *                     4=orientation_change
 */
#include "fault_tree.h"

int fault_tree_classify(const float *f)
{
    if (f[9] <= 30.468500f) { /* temp_c_mean */
        if (f[1] <= 0.002036f) { /* amps_std */
            if (f[7] <= 65.149998f) { /* vib_rms_mean */
                if (f[6] <= 3.950000f) { /* mech1x_mean */
                    if (f[5] <= 254.000000f) { /* ripple_mean */
                        if (f[4] <= 4.952243f) { /* rpm_std */
                            return 2; /* rotor_drag */
                        } else {
                            return 0; /* healthy */
                        }
                    } else {
                        return 0; /* healthy */
                    }
                } else {
                    if (f[9] <= 24.426500f) { /* temp_c_mean */
                        if (f[9] <= 23.482500f) { /* temp_c_mean */
                            return 4; /* orientation_change */
                        } else {
                            if (f[2] <= 0.080300f) { /* amps_max */
                                return 0; /* healthy */
                            } else {
                                return 2; /* rotor_drag */
                            }
                        }
                    } else {
                        if (f[0] <= 0.095640f) { /* amps_mean */
                            if (f[7] <= 62.049999f) { /* vib_rms_mean */
                                return 1; /* loose_mount */
                            } else {
                                return 1; /* loose_mount */
                            }
                        } else {
                            return 2; /* rotor_drag */
                        }
                    }
                }
            } else {
                if (f[8] <= 238.500000f) { /* vib_pk_max */
                    if (f[7] <= 67.049999f) { /* vib_rms_mean */
                        if (f[3] <= 616.450012f) { /* rpm_mean */
                            if (f[3] <= 405.399994f) { /* rpm_mean */
                                return 0; /* healthy */
                            } else {
                                return 4; /* orientation_change */
                            }
                        } else {
                            if (f[9] <= 23.783000f) { /* temp_c_mean */
                                return 4; /* orientation_change */
                            } else {
                                return 0; /* healthy */
                            }
                        }
                    } else {
                        if (f[7] <= 68.549999f) { /* vib_rms_mean */
                            if (f[9] <= 24.283500f) { /* temp_c_mean */
                                return 4; /* orientation_change */
                            } else {
                                return 0; /* healthy */
                            }
                        } else {
                            if (f[5] <= 298.500000f) { /* ripple_mean */
                                return 4; /* orientation_change */
                            } else {
                                return 1; /* loose_mount */
                            }
                        }
                    }
                } else {
                    if (f[3] <= 1713.799988f) { /* rpm_mean */
                        return 2; /* rotor_drag */
                    } else {
                        if (f[6] <= 1.000000f) { /* mech1x_mean */
                            return 2; /* rotor_drag */
                        } else {
                            if (f[0] <= 0.061360f) { /* amps_mean */
                                return 1; /* loose_mount */
                            } else {
                                return 1; /* loose_mount */
                            }
                        }
                    }
                }
            }
        } else {
            if (f[2] <= 0.101100f) { /* amps_max */
                if (f[9] <= 25.497500f) { /* temp_c_mean */
                    if (f[9] <= 24.012000f) { /* temp_c_mean */
                        if (f[8] <= 139.000000f) { /* vib_pk_max */
                            return 0; /* healthy */
                        } else {
                            return 4; /* orientation_change */
                        }
                    } else {
                        if (f[9] <= 24.542500f) { /* temp_c_mean */
                            if (f[4] <= 19.494708f) { /* rpm_std */
                                return 2; /* rotor_drag */
                            } else {
                                return 0; /* healthy */
                            }
                        } else {
                            if (f[2] <= 0.076500f) { /* amps_max */
                                return 1; /* loose_mount */
                            } else {
                                return 0; /* healthy */
                            }
                        }
                    }
                } else {
                    if (f[5] <= 408.899994f) { /* ripple_mean */
                        return 2; /* rotor_drag */
                    } else {
                        if (f[9] <= 25.783500f) { /* temp_c_mean */
                            return 4; /* orientation_change */
                        } else {
                            return 0; /* healthy */
                        }
                    }
                }
            } else {
                if (f[9] <= 23.746500f) { /* temp_c_mean */
                    if (f[3] <= 401.099991f) { /* rpm_mean */
                        return 2; /* rotor_drag */
                    } else {
                        return 4; /* orientation_change */
                    }
                } else {
                    if (f[4] <= 566.521362f) { /* rpm_std */
                        return 2; /* rotor_drag */
                    } else {
                        if (f[0] <= 0.203975f) { /* amps_mean */
                            return 1; /* loose_mount */
                        } else {
                            return 2; /* rotor_drag */
                        }
                    }
                }
            }
        }
    } else {
        if (f[6] <= 0.350000f) { /* mech1x_mean */
            if (f[5] <= 304.350006f) { /* ripple_mean */
                return 2; /* rotor_drag */
            } else {
                if (f[4] <= 17.003095f) { /* rpm_std */
                    if (f[8] <= 299.000000f) { /* vib_pk_max */
                        if (f[1] <= 0.001125f) { /* amps_std */
                            if (f[9] <= 31.517000f) { /* temp_c_mean */
                                return 3; /* overheat */
                            } else {
                                return 2; /* rotor_drag */
                            }
                        } else {
                            return 3; /* overheat */
                        }
                    } else {
                        return 2; /* rotor_drag */
                    }
                } else {
                    return 2; /* rotor_drag */
                }
            }
        } else {
            return 2; /* rotor_drag */
        }
    }
}
