/* AUTO-GENERATED by tools/train_model.py; DO NOT EDIT.
 * Depth-7 decision tree, 35 nodes, held-out window accuracy 0.9997.
 * Input: float f[16] in the exact order of model/features.json.
 * Returns fault code: 0=healthy 1=loose_mount 2=rotor_drag 3=overheat
 *                     4=orientation_change
 */
#include "fault_tree.h"

int fault_tree_classify(const float *f)
{
    if (f[14] <= 48.056829f) { /* tilt_deg */
        if (f[14] <= 1.232976f) { /* tilt_deg */
            if (f[2] <= 0.135250f) { /* amps_max */
                if (f[14] <= 0.180055f) { /* tilt_deg */
                    return 0; /* healthy */
                } else {
                    return 0; /* healthy */
                }
            } else {
                return 2; /* rotor_drag */
            }
        } else {
            if (f[6] <= 0.350000f) { /* mech1x_mean */
                if (f[5] <= 304.350006f) { /* ripple_mean */
                    return 2; /* rotor_drag */
                } else {
                    if (f[8] <= 224.000000f) { /* vib_pk_max */
                        if (f[4] <= 17.003095f) { /* rpm_std */
                            if (f[11] <= 15.950000f) { /* grav_x_mean */
                                return 2; /* rotor_drag */
                            } else {
                                return 3; /* overheat */
                            }
                        } else {
                            return 2; /* rotor_drag */
                        }
                    } else {
                        return 2; /* rotor_drag */
                    }
                }
            } else {
                if (f[12] <= 84.049999f) { /* grav_y_mean */
                    if (f[12] <= 83.000000f) { /* grav_y_mean */
                        if (f[14] <= 1.336397f) { /* tilt_deg */
                            if (f[1] <= 0.000871f) { /* amps_std */
                                return 0; /* healthy */
                            } else {
                                return 2; /* rotor_drag */
                            }
                        } else {
                            if (f[6] <= 0.750000f) { /* mech1x_mean */
                                return 2; /* rotor_drag */
                            } else {
                                return 2; /* rotor_drag */
                            }
                        }
                    } else {
                        if (f[8] <= 646.500000f) { /* vib_pk_max */
                            return 1; /* loose_mount */
                        } else {
                            return 2; /* rotor_drag */
                        }
                    }
                } else {
                    if (f[8] <= 516.000000f) { /* vib_pk_max */
                        if (f[10] <= -0.715000f) { /* temp_slope_c_per_s */
                            return 1; /* loose_mount */
                        } else {
                            return 1; /* loose_mount */
                        }
                    } else {
                        return 2; /* rotor_drag */
                    }
                }
            }
        }
    } else {
        return 4; /* orientation_change */
    }
}
