"""Generate the TIM3_CH1 PWM speed table and build command."""

import os

# The BLD-510B SV input is referenced to 5 V but the F401 PWM swings 3.3 V,
# so effective full-scale = 3500 * 3.3/5 = 2310 rpm (bench-verified 2026-07-17:
# S1200 -> 804 measured = x0.67). Commanded rpm above this is unreachable.
DRIVER_FULLSCALE_RPM = 2310
PWM_PERIOD_TICKS = 1000
PWM_TICKS_PER_RPM = PWM_PERIOD_TICKS / DRIVER_FULLSCALE_RPM
RPM_CEILING = DRIVER_FULLSCALE_RPM
HEADER_NAME = "speeds_gen.h"


def rpm_to_pwm(rpm):
    try:
        rpm = float(rpm)
    except (TypeError, ValueError):
        rpm = 0.0
    return max(0, min(PWM_PERIOD_TICKS, int(round(rpm * PWM_TICKS_PER_RPM))))


# Compatibility for any older UI/imports that still call this name.
rpm_to_dac = rpm_to_pwm


def over_ceiling(rpm):
    try:
        return float(rpm) > RPM_CEILING
    except (TypeError, ValueError):
        return False


def write_speed_table(firmware_dir, rpms):
    """
    rpms: list of up to 5 active setpoints (the 6th step is always OFF).
    Returns (header_path, pwm_ticks). Pads to 5 active + 1 OFF entry.
    """
    active = [rpm_to_pwm(r) for r in rpms if str(r).strip() != ""][:5]
    if not active:
        active = [rpm_to_pwm(500)]
    while len(active) < 5:
        active.append(active[-1])
    codes = active + [0]                            # 6th = OFF / coast-down
    body = ", ".join(f"{c}u" for c in codes)
    text = (
        "/* AUTO-GENERATED by the BLDC PHM app; do not hand-edit.\n"
        " * Change speeds in the app; it regenerates this and reflashes. */\n"
        "#ifndef SPEEDS_GEN_H\n#define SPEEDS_GEN_H\n"
        f"/* TIM3_CH1 PWM ticks (PB4 / D5); 1000 = 100% = {RPM_CEILING} rpm */\n"
        f"static const unsigned short SPEED_TABLE[6] = {{ {body} }};\n"
        "#endif\n"
    )
    path = os.path.join(firmware_dir, HEADER_NAME)
    with open(path, "w") as f:
        f.write(text)
    return path, codes


def build_command(gcc, firmware_dir):
    """Mirror the project's 1_build.bat gcc invocation. Returns (exe, args, elf_path)."""
    ld = os.path.join(firmware_dir, "STM32F401RE.ld")
    main_c = os.path.join(firmware_dir, "main.c")
    tree_c = os.path.join(firmware_dir, "fault_tree.c")
    elf = os.path.join(firmware_dir, "motor.elf")
    args = ["-mcpu=cortex-m4", "-mthumb", "-ffreestanding", "-nostdlib", "-nostartfiles",
            "-O2", "-Wall", "-Wextra", "-ffunction-sections", "-fdata-sections",
            "-T", ld, main_c]
    if os.path.exists(tree_c):
        args += [tree_c]              # the trained fault classifier, when present
    args += ["-o", elf, "-Wl,--gc-sections",
            # Ratiometric ADC/current conversion uses exact 64-bit integer
            # division. With -nostdlib GCC does not add its compiler runtime
            # automatically, so request libgcc explicitly.
            "-lgcc"]
    return gcc, args, elf
