/* AUTO-GENERATED by the BLDC PHM app; do not hand-edit.
 * Change speeds in the app; it regenerates this and reflashes. */
#ifndef SPEEDS_GEN_H
#define SPEEDS_GEN_H
/* TIM3_CH1 PWM ticks (PB4 / D5); 1000 = 100% = 2310 rpm */
static const unsigned short SPEED_TABLE[6] = { 216u, 346u, 476u, 606u, 736u, 0u };
#endif
