/* NUCLEO-G474RE (MB1367D) + BLD-510B + 42BL41.010 predictive-monitor node
 *
 * Drives motor (TIM3_CH2 PWM on PA7; button steps) and reads motor Halls
 * to compute RPM, speed ripple, Hall health, coast-down. Streams CSV out the
 * ST-Link Virtual COM port (USART2, PA2/PA3) at 115200 8N1, ~10 rows/sec.
 *
 * Wiring (driver and Nucleo grounds must be common):
 *   driver HA/HB/HC -> PA8, PA9, PA10  (D7, D8, D2; timer-capable inputs)
 *   SV speed wire    -> PA7             (D11, TIM3_CH2, 1 kHz PWM)
 *   blue USER button (PC13) steps speed: 500/800/1100/1400/1700/OFF
 *   LD2               -> PA5
 *
 * CSV columns: t_ms,rpm,ripple_permil,min_us,max_us,hall,illegal,edges,step,coast_ms,
 *              period_std_permil,mech1x_permil,elec_permil,i_dc_mv,adc_vref_raw,adc_pc0_mv
 * 8-pole motor = 4 pole-pairs -> 24 Hall edges per mechanical revolution.
 *   period_std_permil : std of the 24 edge intervals / mean (overall timing jitter)
 *   mech1x_permil     : amplitude of the 1x-MECHANICAL component (24-edge period) /mean
 *                       -> imbalance / eccentricity signature
 *   elec_permil       : amplitude of the ELECTRICAL component (6-edge period, bin 4) /mean
 *                       -> Hall-spacing / electrical-asymmetry signature
 * Separating these two keeps permanent Hall/magnet spacing from masquerading as
 * mechanical 1x. All features are integer-only (soft-float build). Computed once per
 * revolution from the 24 edge intervals via an integer DFT (Q10 cos/sin tables).
 * Clock = reset-default HSI16 (16 MHz); TIM2 = 1 us timebase.
 * TIM3 PWM = 1 kHz with 1000 duty ticks; USART2 kernel clock = 16 MHz.
 */
#include <stdint.h>
#include "speeds_gen.h"   /* SPEED_TABLE[6], regenerated by the BLDC PHM app */

#define RCC_AHB2ENR   (*(volatile uint32_t *)0x4002104Cu) /* GPIOA b0, GPIOC b2, ADC12 b13 */
#define RCC_APB1ENR1  (*(volatile uint32_t *)0x40021058u) /* TIM2 b0, TIM3 b1, USART2 b17 */
#define GPIOA_MODER   (*(volatile uint32_t *)0x48000000u)
#define GPIOA_PUPDR   (*(volatile uint32_t *)0x4800000Cu)
#define GPIOA_IDR     (*(volatile uint32_t *)0x48000010u)
#define GPIOA_BSRR    (*(volatile uint32_t *)0x48000018u)
#define GPIOA_AFRL    (*(volatile uint32_t *)0x48000020u)
#define GPIOC_MODER   (*(volatile uint32_t *)0x48000800u)
#define GPIOC_PUPDR   (*(volatile uint32_t *)0x4800080Cu)
#define GPIOC_IDR     (*(volatile uint32_t *)0x48000810u)

#define ADC1_ISR      (*(volatile uint32_t *)0x50000000u)
#define ADC1_CR       (*(volatile uint32_t *)0x50000008u)
#define ADC1_CFGR     (*(volatile uint32_t *)0x5000000Cu)
#define ADC1_SMPR1    (*(volatile uint32_t *)0x50000014u)
#define ADC1_SMPR2    (*(volatile uint32_t *)0x50000018u)
#define ADC1_SQR1     (*(volatile uint32_t *)0x50000030u)
#define ADC1_DIFSEL   (*(volatile uint32_t *)0x500000B0u)
#define ADC1_DR       (*(volatile uint32_t *)0x50000040u)
#define ADC12_CCR     (*(volatile uint32_t *)0x50000308u)

#define TIM2_CR1      (*(volatile uint32_t *)0x40000000u)
#define TIM2_EGR      (*(volatile uint32_t *)0x40000014u)
#define TIM2_CNT      (*(volatile uint32_t *)0x40000024u)
#define TIM2_PSC      (*(volatile uint32_t *)0x40000028u)
#define TIM2_ARR      (*(volatile uint32_t *)0x4000002Cu)

#define TIM3_CR1      (*(volatile uint32_t *)0x40000400u)
#define TIM3_EGR      (*(volatile uint32_t *)0x40000414u)
#define TIM3_CCMR1    (*(volatile uint32_t *)0x40000418u)
#define TIM3_CCER     (*(volatile uint32_t *)0x40000420u)
#define TIM3_PSC      (*(volatile uint32_t *)0x40000428u)
#define TIM3_ARR      (*(volatile uint32_t *)0x4000042Cu)
#define TIM3_CCR2     (*(volatile uint32_t *)0x40000438u)

#define USART2_CR1    (*(volatile uint32_t *)0x40004400u)
#define USART2_BRR    (*(volatile uint32_t *)0x4000440Cu)
#define USART2_ISR    (*(volatile uint32_t *)0x4000441Cu)
#define USART2_RDR    (*(volatile uint32_t *)0x40004424u)
#define USART2_TDR    (*(volatile uint32_t *)0x40004428u)

#define PWM_PERIOD_TICKS 1000u

volatile uint32_t g_tlm[16];
enum { T_RPM=0,T_AVG_US,T_MIN_US,T_MAX_US,T_RIPPLE,T_EDGES,T_STATE,
       T_ILLEGAL,T_COAST_MS,T_RPM_ATCUT,T_SPEEDIDX,
       T_PSTD,T_MECH1X,T_ELEC };

/* Q10 (x1024) cos/sin tables for a 24-point DFT, bins k=1 (mechanical 1x) and
 * k=4 (electrical, 6-edge period). Generated + validated against numpy in the host. */
static const short C1[24]={1024,989,887,724,512,265,0,-265,-512,-724,-887,-989,-1024,-989,-887,-724,-512,-265,0,265,512,724,887,989};
static const short S1[24]={0,265,512,724,887,989,1024,989,887,724,512,265,0,-265,-512,-724,-887,-989,-1024,-989,-887,-724,-512,-265};
static const short C4[24]={1024,512,-512,-1024,-512,512,1024,512,-512,-1024,-512,512,1024,512,-512,-1024,-512,512,1024,512,-512,-1024,-512,512};
static const short S4[24]={0,887,887,0,-887,-887,0,887,887,0,-887,-887,0,887,887,0,-887,-887,0,887,887,0,-887,-887};

/* integer sqrt of a 64-bit value */
static uint32_t isqrt64(uint64_t x)
{
    uint64_t r = 0u, b = 1ull << 62;
    while (b > x) b >>= 2;
    while (b) {
        if (x >= r + b) { x -= r + b; r = (r >> 1) + b; }
        else r >>= 1;
        b >>= 2;
    }
    return (uint32_t)r;
}

/* amplitude of DFT bin (table C,S) as per-mille of the mean interval.
 * permil = 1000*(2/24)*|DFT_k|/mean = 2000*mag/(1024*ssum), mag = 1024*|DFT_k|. */
static uint32_t amp_permil(const uint32_t *d, const short *C, const short *S, uint32_t ssum)
{
    int64_t re = 0, im = 0;
    for (int n = 0; n < 24; n++) { re += (int64_t)d[n] * C[n]; im += (int64_t)d[n] * S[n]; }
    uint32_t mag = isqrt64((uint64_t)(re * re) + (uint64_t)(im * im));   /* = 1024*|DFT_k| */
    /* permil = 2000*mag/(1024*ssum) = (125*mag>>6)/ssum; kept 32-bit (M4 has UDIV,
     * no 64-bit divide helper under -nostdlib). */
    uint32_t num = (uint32_t)(((uint64_t)125u * mag) >> 6);
    return ssum ? num / ssum : 0u;
}

static inline uint32_t now_us(void) { return TIM2_CNT; }
static inline uint32_t hall_state(void) { return (GPIOA_IDR >> 8) & 0x7u; }
static inline uint32_t button(void) { return (GPIOC_IDR >> 13) & 1u; }

static void set_speed(uint16_t pwm_ticks)
{
    if (pwm_ticks > PWM_PERIOD_TICKS) pwm_ticks = PWM_PERIOD_TICKS;
    TIM3_CCR2 = pwm_ticks;
    if (pwm_ticks) { GPIOA_BSRR = (1u << 5); } else { GPIOA_BSRR = (1u << 21); }
}

static void current_adc_init(void)
{
    /* ADC1_IN1 on PA0/A0, single-ended, synchronous 16 MHz ADC clock. */
    ADC12_CCR = (ADC12_CCR & ~(3u << 16)) | (1u << 16) | (1u << 22); /* HCLK/1 + VREFINT */
    ADC1_CR &= ~(1u << 29);                              /* leave deep power-down */
    ADC1_CR |= (1u << 28);                              /* enable ADC regulator */
    uint32_t t0 = now_us();
    while ((now_us() - t0) < 25u) { }                   /* regulator stabilization */

    ADC1_DIFSEL &= ~(1u << 1);                          /* channel 1 single-ended */
    ADC1_CR &= ~(1u << 30);                             /* single-ended calibration */
    ADC1_CR |= (1u << 31);                              /* ADCAL */
    while (ADC1_CR & (1u << 31)) { }
    t0 = now_us();
    while ((now_us() - t0) < 2u) { }

    ADC1_CFGR = 0u;                                     /* 12-bit, software trigger */
    ADC1_SMPR1 = (ADC1_SMPR1 & ~(7u << 3)) | (4u << 3); /* ch1: 47.5 cycles */
    ADC1_SMPR1 = (ADC1_SMPR1 & ~(7u << 18)) | (4u << 18); /* ch6/PC0: 47.5 cycles */
    ADC1_SMPR2 = (ADC1_SMPR2 & ~(7u << 24)) | (7u << 24); /* ch18 VREF: 640.5 cycles */
    ADC1_SQR1 = (1u << 6);                              /* one conversion, SQ1=IN1 */
    ADC1_ISR = 1u;                                      /* clear ADRDY */
    ADC1_CR |= 1u;                                      /* ADEN */
    while (!(ADC1_ISR & 1u)) { }
}

static uint32_t adc_read_channel(uint32_t channel)
{
    ADC1_SQR1 = (channel & 0x1Fu) << 6;
    ADC1_CR |= (1u << 2);                               /* ADSTART */
    uint32_t t0 = now_us();
    while (!(ADC1_ISR & (1u << 2))) {                   /* EOC */
        if ((now_us() - t0) > 100u) return 0u;
    }
    return ADC1_DR & 0x0FFFu;
}

/* append unsigned decimal to buf at pos, return new pos */
static int ap_u(char *b, int p, uint32_t v)
{
    char tmp[10]; int n = 0;
    if (v == 0u) { b[p++] = '0'; return p; }
    while (v) { tmp[n++] = (char)('0' + (v % 10u)); v /= 10u; }
    while (n) { b[p++] = tmp[--n]; }
    return p;
}

int main(void)
{
    RCC_AHB2ENR  |= (1u << 0) | (1u << 2) | (1u << 13); /* GPIOA + GPIOC + ADC12 */
    RCC_APB1ENR1 |= (1u << 0) | (1u << 1) | (1u << 17); /* TIM2 + TIM3 + USART2 */
    (void)RCC_APB1ENR1;                                  /* clock-enable readback */

    /* PA7 = TIM3_CH2 (AF2) PWM; PA2/PA3 = USART2 TX/RX (AF7). */
    GPIOA_MODER = (GPIOA_MODER & ~((3u << 14) | (3u << 4) | (3u << 6))) |
                  (2u << 14) | (2u << 4) | (2u << 6);
    GPIOA_AFRL = (GPIOA_AFRL & ~((0xFu << 28) | (0xFu << 8) | (0xFu << 12))) |
                 (2u << 28) | (7u << 8) | (7u << 12);

    /* PA8/PA9/PA10 Hall GPIO inputs with pull-ups. These pins are also
     * TIM1_CH1/CH2/CH3 capable, but polling all three preserves the existing
     * any-edge timing and Hall-state validation. */
    GPIOA_MODER &= ~((3u << 16) | (3u << 18) | (3u << 20));
    GPIOA_PUPDR = (GPIOA_PUPDR & ~((3u << 16) | (3u << 18) | (3u << 20))) |
                  (1u << 16) | (1u << 18) | (1u << 20);

    /* LD2 on PA5. */
    GPIOA_MODER = (GPIOA_MODER & ~(3u << 10)) | (1u << 10);

    /* Button PC13 input pull-down */
    GPIOC_MODER  &= ~(3u << 26);
    GPIOC_PUPDR   = (GPIOC_PUPDR & ~(3u << 26)) | (2u << 26);

    /* USART2 115200 8N1, TX + RX (RX = PC speed commands over the same VCP). */
    USART2_CR1 = 0u;
    USART2_BRR = 139u;                 /* round(16 MHz / 115200) */
    USART2_CR1 = (1u << 3) | (1u << 2) | (1u << 0); /* TE | RE | UE */

    /* TIM2 1 us free-run */
    TIM2_PSC = 15u; TIM2_ARR = 0xFFFFFFFFu; TIM2_EGR = 1u; TIM2_CR1 = 1u;

    /* PA0/A0 = ADC12_IN1 current-sensor input, no pull. PC0/A5 is sampled only
     * as a diagnostic for installations that may still be wired to the old pin. */
    GPIOA_MODER |= (3u << 0);
    GPIOA_PUPDR &= ~(3u << 0);
    GPIOC_MODER |= (3u << 0);
    GPIOC_PUPDR &= ~(3u << 0);
    current_adc_init();

    /* TIM3_CH2 PWM mode 1: 16 MHz / 16 / 1000 = 1 kHz. */
    TIM3_PSC = 15u;
    TIM3_ARR = PWM_PERIOD_TICKS - 1u;
    TIM3_CCR2 = 0u;
    TIM3_CCMR1 = (6u << 12) | (1u << 11); /* OC2M=PWM1, OC2PE=1 */
    TIM3_CCER = (1u << 4);                 /* CC2E */
    TIM3_EGR = 1u;
    TIM3_CR1 = (1u << 7) | 1u;            /* ARPE + CEN */

    const uint16_t *table = SPEED_TABLE;   /* from speeds_gen.h (app-generated) */
    uint32_t idx = 5u;                     /* safe reset state: OFF */
    set_speed(table[idx]);
    g_tlm[T_SPEEDIDX] = idx;

    uint32_t last_state = hall_state();
    uint32_t last_edge  = now_us();
    uint32_t ema_us = 0u, win_sum = 0u, win_cnt = 0u;
    uint64_t win_sq = 0u;                 /* sum of dt^2 over the rev (for std) */
    uint32_t ring[24];                    /* the 24 edge intervals of the current rev */
    uint32_t win_min = 0xFFFFFFFFu, win_max = 0u;
    uint32_t edges = 0u, illegal = 0u;
    uint32_t btn_prev = 0u, btn_t = 0u;
    uint32_t coasting = 0u, coast_t0 = 0u;

    char txbuf[160]; int txlen = 0, txpos = 0;
    uint32_t last_print = 0u;
    uint32_t last_adc = 0u, current_ema_q8 = 0u, pc0_ema_q8 = 0u;
    char cmdbuf[16]; int cmdlen = 0;     /* serial RX line buffer for "S<rpm>" */

    for (;;) {
        uint32_t t = now_us();
        uint32_t s = hall_state();

        /* Sample PA0 at 1 kHz and smooth it before the 10 Hz telemetry stream. */
        if ((t - last_adc) >= 1000u) {
            last_adc = t;
            uint32_t raw = adc_read_channel(1u);
            current_ema_q8 = current_ema_q8
                ? current_ema_q8 - (current_ema_q8 >> 4) + (raw << 4)
                : (raw << 8);
            raw = adc_read_channel(6u);
            pc0_ema_q8 = pc0_ema_q8
                ? pc0_ema_q8 - (pc0_ema_q8 >> 4) + (raw << 4)
                : (raw << 8);
        }

        /* Hall edge (filtered) */
        if (s != last_state) {
            if (s == 0u || s == 7u) {
                illegal++; g_tlm[T_ILLEGAL] = illegal; last_state = s;
            } else {
                uint32_t dt = t - last_edge;
                if (dt >= 100u) {
                    last_edge = t; last_state = s; edges++;
                    ema_us = ema_us ? (ema_us - (ema_us >> 3) + (dt >> 3)) : dt;
                    if (dt < win_min) win_min = dt;
                    if (dt > win_max) win_max = dt;
                    ring[win_cnt] = dt;
                    win_sum += dt;
                    win_sq  += (uint64_t)dt * dt;
                    if (++win_cnt >= 24u) {
                        uint32_t avg = win_sum / 24u;
                        g_tlm[T_RPM]    = win_sum ? (60000000u / win_sum) : 0u;
                        g_tlm[T_AVG_US] = avg;
                        g_tlm[T_MIN_US] = win_min;
                        g_tlm[T_MAX_US] = win_max;
                        g_tlm[T_RIPPLE] = avg ? ((win_max - win_min) * 1000u / avg) : 0u;
                        /* per-rev Hall features (integer DFT over the 24 intervals).
                         * variance = (24*Sxx - S^2)/576 = ((tot>>6)/9), all 32-bit divides. */
                        uint64_t tot = 24ull * win_sq - (uint64_t)win_sum * win_sum;
                        uint32_t var = (uint32_t)(tot >> 6) / 9u;
                        uint32_t sd = isqrt64(var);
                        g_tlm[T_PSTD]   = win_sum ? (1000u * 24u * sd) / win_sum : 0u;
                        g_tlm[T_MECH1X] = amp_permil(ring, C1, S1, win_sum);
                        g_tlm[T_ELEC]   = amp_permil(ring, C4, S4, win_sum);
                        win_sum = 0u; win_sq = 0u; win_cnt = 0u;
                        win_min = 0xFFFFFFFFu; win_max = 0u;
                    }
                    g_tlm[T_EDGES] = edges; g_tlm[T_STATE] = s;
                } else { last_state = s; }
            }
        }

        /* stopped detection */
        if ((t - last_edge) > 300000u) {
            g_tlm[T_RPM] = 0u;
            if (coasting) { g_tlm[T_COAST_MS] = (last_edge - coast_t0) / 1000u; coasting = 0u; }
        }

        /* button */
        uint32_t b = button();
        if (b && !btn_prev && (t - btn_t) > 200000u) {
            btn_t = t; idx = (idx + 1u) % 6u; set_speed(table[idx]);
            g_tlm[T_SPEEDIDX] = idx;
            if (table[idx] == 0u) { coast_t0 = t; g_tlm[T_RPM_ATCUT] = g_tlm[T_RPM]; coasting = 1u; }
            else { coasting = 0u; }
        }
        btn_prev = b;

        /* serial RX: live speed command "S<rpm>" (e.g. S1500\n) */
        if (USART2_ISR & (1u << 5)) {                 /* RXNE: a byte arrived */
            char c = (char)USART2_RDR;                /* read clears RXNE */
            if (c == '\r' || c == '\n') {
                if (cmdlen > 0 && (cmdbuf[0] == 'S' || cmdbuf[0] == 's')) {
                    uint32_t rpm = 0u;
                    for (int k = 1; k < cmdlen; k++)
                        if (cmdbuf[k] >= '0' && cmdbuf[k] <= '9')
                            rpm = rpm * 10u + (uint32_t)(cmdbuf[k] - '0');
                    uint32_t pwm = (rpm * PWM_PERIOD_TICKS + 1750u) / 3500u;
                    if (pwm > PWM_PERIOD_TICKS) pwm = PWM_PERIOD_TICKS;
                    set_speed((uint16_t)pwm);
                    g_tlm[T_SPEEDIDX] = 9u;            /* 9 = serial-commanded speed */
                    /* commanding S0 over serial starts a coast-down measurement too
                     * (mirrors the button OFF step) so the app can run coast tests */
                    if (rpm == 0u) { coast_t0 = t; g_tlm[T_RPM_ATCUT] = g_tlm[T_RPM]; coasting = 1u; }
                    else { coasting = 0u; }
                }
                cmdlen = 0;
            } else if (cmdlen < 15) {
                cmdbuf[cmdlen++] = c;
            }
        }

        /* non-blocking UART CSV stream */
        if (txpos < txlen) {
            if (USART2_ISR & (1u << 7)) { USART2_TDR = (uint8_t)txbuf[txpos++]; }
        } else if ((t - last_print) > 100000u) {       /* new row every 100 ms */
            last_print = t;
            int p = 0;
            p = ap_u(txbuf, p, t / 1000u);            txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_RPM]);         txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_RIPPLE]);      txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_MIN_US]);      txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_MAX_US]);      txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_STATE]);       txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_ILLEGAL]);     txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_EDGES]);       txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_SPEEDIDX]);    txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_COAST_MS]);    txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_PSTD]);        txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_MECH1X]);      txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_ELEC]);        txbuf[p++] = ',';
            uint32_t current_mv = ((current_ema_q8 >> 8) * 3300u + 2047u) / 4095u;
            p = ap_u(txbuf, p, current_mv);            txbuf[p++] = ',';
            p = ap_u(txbuf, p, adc_read_channel(18u)); txbuf[p++] = ',';
            uint32_t pc0_mv = ((pc0_ema_q8 >> 8) * 3300u + 2047u) / 4095u;
            p = ap_u(txbuf, p, pc0_mv);                 txbuf[p++] = '\r'; txbuf[p++] = '\n';
            txlen = p; txpos = 0;
        }
    }
}

/* minimal startup */
extern uint32_t _sidata, _sdata, _edata, _sbss, _ebss, _estack;

void Reset_Handler(void)
{
    uint32_t *src = &_sidata, *dst = &_sdata;
    while (dst < &_edata) { *dst++ = *src++; }
    for (dst = &_sbss; dst < &_ebss;) { *dst++ = 0; }
    main();
    for (;;) { }
}

void Default_Handler(void) { for (;;) { } }

typedef void (*vec_t)(void);
__attribute__((section(".isr_vector"), used))
const vec_t vector_table[] = {
    (vec_t)(&_estack),
    Reset_Handler,
    Default_Handler, Default_Handler, Default_Handler,
    Default_Handler, Default_Handler,
    0, 0, 0, 0,
    Default_Handler, Default_Handler,
    0,
    Default_Handler, Default_Handler,
};
