/* NUCLEO-H743ZI2 + BLD-510B + 42BL41.010: predictive-monitor data node
 *
 * Drives motor (DAC speed PA5, PA4 spare; button steps) and reads motor Halls
 * to compute RPM, speed ripple, Hall health, coast-down. Streams CSV out the
 * ST-Link Virtual COM port (USART3, PD8) at 115200 8N1, ~10 rows/sec.
 *
 * Wiring (GND already common):
 *   driver HA/HB/HC -> PD5, PD6, PD7   (any order, 5V-tolerant)
 *   SV speed wire    -> PA5 (DAC1_OUT2)
 *   blue USER button (PC13) steps speed: 500/800/1100/1400/1700/OFF
 *
 * CSV columns: t_ms,rpm,ripple_permil,min_us,max_us,hall,illegal,edges,step,coast_ms
 * 8-pole motor = 4 pole-pairs -> 24 Hall edges per mechanical revolution.
 * Clock = HSI 64 MHz; TIM2 = 1 us timebase; USART kernel clock = 64 MHz.
 */
#include <stdint.h>
#include "speeds_gen.h"   /* SPEED_TABLE[6], regenerated by the BLDC PHM app */

#define RCC_AHB4ENR   (*(volatile uint32_t *)0x580244E0u)
#define RCC_APB1LENR  (*(volatile uint32_t *)0x580244E8u) /* TIM2 b0, USART3 b18, DAC b29 */
#define GPIOA_MODER   (*(volatile uint32_t *)0x58020000u)
#define GPIOB_MODER   (*(volatile uint32_t *)0x58020400u)
#define GPIOB_BSRR    (*(volatile uint32_t *)0x58020418u)
#define GPIOC_MODER   (*(volatile uint32_t *)0x58020800u)
#define GPIOC_PUPDR   (*(volatile uint32_t *)0x5802080Cu)
#define GPIOC_IDR     (*(volatile uint32_t *)0x58020810u)
#define GPIOD_MODER   (*(volatile uint32_t *)0x58020C00u) /* PD5/6/7 in, PD8 AF */
#define GPIOD_PUPDR   (*(volatile uint32_t *)0x58020C0Cu)
#define GPIOD_IDR     (*(volatile uint32_t *)0x58020C10u)
#define GPIOD_AFRH    (*(volatile uint32_t *)0x58020C24u) /* PD8 alt func */
#define DAC1_CR       (*(volatile uint32_t *)0x40007400u)
#define DAC1_MCR      (*(volatile uint32_t *)0x4000743Cu)
#define DAC1_DHR12R1  (*(volatile uint32_t *)0x40007408u) /* PA4 */
#define DAC1_DHR12R2  (*(volatile uint32_t *)0x40007414u) /* PA5 */

#define TIM2_CR1      (*(volatile uint32_t *)0x40000000u)
#define TIM2_EGR      (*(volatile uint32_t *)0x40000014u)
#define TIM2_CNT      (*(volatile uint32_t *)0x40000024u)
#define TIM2_PSC      (*(volatile uint32_t *)0x40000028u)
#define TIM2_ARR      (*(volatile uint32_t *)0x4000002Cu)

#define USART3_CR1    (*(volatile uint32_t *)0x40004800u)
#define USART3_BRR    (*(volatile uint32_t *)0x4000480Cu)
#define USART3_ISR    (*(volatile uint32_t *)0x4000481Cu)
#define USART3_TDR    (*(volatile uint32_t *)0x40004828u)
#define USART3_RDR    (*(volatile uint32_t *)0x40004824u)

volatile uint32_t g_tlm[16];
enum { T_RPM=0,T_AVG_US,T_MIN_US,T_MAX_US,T_RIPPLE,T_EDGES,T_STATE,
       T_ILLEGAL,T_COAST_MS,T_RPM_ATCUT,T_SPEEDIDX };

static inline uint32_t now_us(void) { return TIM2_CNT; }
static inline uint32_t hall_state(void) { return (GPIOD_IDR >> 5) & 0x7u; }
static inline uint32_t button(void) { return (GPIOC_IDR >> 13) & 1u; }

static void set_speed(uint16_t dac)
{
    DAC1_DHR12R1 = dac;
    DAC1_DHR12R2 = dac;
    if (dac) { GPIOB_BSRR = (1u << 0); } else { GPIOB_BSRR = (1u << 16); }
}

/* append unsigned decimal to buf at pos, return new pos */
static int ap_u(char *b, int p, uint32_t v)
{
    char tmp[10]; int n = 0;
    if (v == 0u) { b[p++] = '0'; return p; }
    while (v) { tmp[n++] = (char)('0' + (v % 10u)); v /= 10u; }
    while (n) { b[p++] = tmp[--n]; }
    return p;
}

int main(void)
{
    RCC_AHB4ENR  |= 0xFu;                                /* GPIOA+B+C+D */
    RCC_APB1LENR |= (1u<<0) | (1u<<18) | (1u<<29);       /* TIM2 + USART3 + DAC */

    /* DAC PA4 + PA5 */
    GPIOA_MODER  |= (3u << 8) | (3u << 10);
    DAC1_MCR     &= ~((7u << 0) | (7u << 16));
    DAC1_CR      |= (1u << 0) | (1u << 16);

    /* LED PB0 */
    GPIOB_MODER   = (GPIOB_MODER & ~(3u << 0)) | (1u << 0);

    /* Button PC13 input pull-down */
    GPIOC_MODER  &= ~(3u << 26);
    GPIOC_PUPDR   = (GPIOC_PUPDR & ~(3u << 26)) | (2u << 26);

    /* Hall inputs PD5/PD6/PD7 pull-up; PD8 = USART3_TX (AF7) */
    GPIOD_MODER  &= ~0xFC00u;
    GPIOD_PUPDR   = (GPIOD_PUPDR & ~0xFC00u) | 0x5400u;
    GPIOD_MODER   = (GPIOD_MODER & ~((3u << 16) | (3u << 18))) | (2u << 16) | (2u << 18); /* PD8 TX, PD9 RX */
    GPIOD_AFRH    = (GPIOD_AFRH & ~0xFFu) | 7u | (7u << 4);     /* PD8,PD9 -> AF7 */

    /* USART3 115200 8N1, TX + RX (RX = PC speed commands over the same VCP) */
    USART3_CR1 = 0u;
    USART3_BRR = 556u;                 /* 64 MHz / 115200 */
    USART3_CR1 = (1u << 3) | (1u << 2) | (1u << 0); /* TE | RE | UE */

    /* TIM2 1 us free-run */
    TIM2_PSC = 63u; TIM2_ARR = 0xFFFFFFFFu; TIM2_EGR = 1u; TIM2_CR1 = 1u;

    const uint16_t *table = SPEED_TABLE;   /* from speeds_gen.h (app-generated) */
    uint32_t idx = 0u;
    set_speed(table[idx]);

    uint32_t last_state = hall_state();
    uint32_t last_edge  = now_us();
    uint32_t ema_us = 0u, win_sum = 0u, win_cnt = 0u;
    uint32_t win_min = 0xFFFFFFFFu, win_max = 0u;
    uint32_t edges = 0u, illegal = 0u;
    uint32_t btn_prev = 0u, btn_t = 0u;
    uint32_t coasting = 0u, coast_t0 = 0u;

    char txbuf[128]; int txlen = 0, txpos = 0;
    uint32_t last_print = 0u;
    char cmdbuf[16]; int cmdlen = 0;     /* serial RX line buffer for "S<rpm>" */

    for (;;) {
        uint32_t t = now_us();
        uint32_t s = hall_state();

        /* Hall edge (filtered) */
        if (s != last_state) {
            if (s == 0u || s == 7u) {
                illegal++; g_tlm[T_ILLEGAL] = illegal; last_state = s;
            } else {
                uint32_t dt = t - last_edge;
                if (dt >= 100u) {
                    last_edge = t; last_state = s; edges++;
                    ema_us = ema_us ? (ema_us - (ema_us >> 3) + (dt >> 3)) : dt;
                    if (dt < win_min) win_min = dt;
                    if (dt > win_max) win_max = dt;
                    win_sum += dt;
                    if (++win_cnt >= 24u) {
                        uint32_t avg = win_sum / 24u;
                        g_tlm[T_RPM]    = win_sum ? (60000000u / win_sum) : 0u;
                        g_tlm[T_AVG_US] = avg;
                        g_tlm[T_MIN_US] = win_min;
                        g_tlm[T_MAX_US] = win_max;
                        g_tlm[T_RIPPLE] = avg ? ((win_max - win_min) * 1000u / avg) : 0u;
                        win_sum = 0u; win_cnt = 0u; win_min = 0xFFFFFFFFu; win_max = 0u;
                    }
                    g_tlm[T_EDGES] = edges; g_tlm[T_STATE] = s;
                } else { last_state = s; }
            }
        }

        /* stopped detection */
        if ((t - last_edge) > 300000u) {
            g_tlm[T_RPM] = 0u;
            if (coasting) { g_tlm[T_COAST_MS] = (last_edge - coast_t0) / 1000u; coasting = 0u; }
        }

        /* button */
        uint32_t b = button();
        if (b && !btn_prev && (t - btn_t) > 200000u) {
            btn_t = t; idx = (idx + 1u) % 6u; set_speed(table[idx]);
            g_tlm[T_SPEEDIDX] = idx;
            if (table[idx] == 0u) { coast_t0 = t; g_tlm[T_RPM_ATCUT] = g_tlm[T_RPM]; coasting = 1u; }
            else { coasting = 0u; }
        }
        btn_prev = b;

        /* serial RX: live speed command "S<rpm>" (e.g. S1500\n) */
        if (USART3_ISR & (1u << 5)) {                 /* RXNE: a byte arrived */
            char c = (char)USART3_RDR;                /* read clears RXNE */
            if (c == '\r' || c == '\n') {
                if (cmdlen > 0 && (cmdbuf[0] == 'S' || cmdbuf[0] == 's')) {
                    uint32_t rpm = 0u;
                    for (int k = 1; k < cmdlen; k++)
                        if (cmdbuf[k] >= '0' && cmdbuf[k] <= '9')
                            rpm = rpm * 10u + (uint32_t)(cmdbuf[k] - '0');
                    uint32_t dac = (rpm * 20475u) / 13200u;   /* DAC = rpm * 1.5511 */
                    if (dac > 4095u) dac = 4095u;
                    set_speed((uint16_t)dac);
                    g_tlm[T_SPEEDIDX] = 9u;            /* 9 = serial-commanded speed */
                }
                cmdlen = 0;
            } else if (cmdlen < 15) {
                cmdbuf[cmdlen++] = c;
            }
        }

        /* non-blocking UART CSV stream */
        if (txpos < txlen) {
            if (USART3_ISR & (1u << 7)) { USART3_TDR = (uint8_t)txbuf[txpos++]; }
        } else if ((t - last_print) > 100000u) {       /* new row every 100 ms */
            last_print = t;
            int p = 0;
            p = ap_u(txbuf, p, t / 1000u);            txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_RPM]);         txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_RIPPLE]);      txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_MIN_US]);      txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_MAX_US]);      txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_STATE]);       txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_ILLEGAL]);     txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_EDGES]);       txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_SPEEDIDX]);    txbuf[p++] = ',';
            p = ap_u(txbuf, p, g_tlm[T_COAST_MS]);    txbuf[p++] = '\r'; txbuf[p++] = '\n';
            txlen = p; txpos = 0;
        }
    }
}

/* minimal startup */
extern uint32_t _sidata, _sdata, _edata, _sbss, _ebss, _estack;

void Reset_Handler(void)
{
    uint32_t *src = &_sidata, *dst = &_sdata;
    while (dst < &_edata) { *dst++ = *src++; }
    for (dst = &_sbss; dst < &_ebss;) { *dst++ = 0; }
    main();
    for (;;) { }
}

void Default_Handler(void) { for (;;) { } }

typedef void (*vec_t)(void);
__attribute__((section(".isr_vector"), used))
const vec_t vector_table[] = {
    (vec_t)(&_estack),
    Reset_Handler,
    Default_Handler, Default_Handler, Default_Handler,
    Default_Handler, Default_Handler,
    0, 0, 0, 0,
    Default_Handler, Default_Handler,
    0,
    Default_Handler, Default_Handler,
};
